version: "3.8"
services:
  genesys:
    build: .
    container_name: genesys_container
    ports:
      - "5008:5008"
    volumes:
      - .:/genesys
    image: genesys:latest
    environment:
      - NODE_ENV=${NODE_ENV:-local}