version: "3.8"
services:
  api:
    build: 
      context: .
      args:
        - BUILD_TIMESTAMP=$(date '+%Y%m%d%H%M%S')
    container_name: genesys_container
    ports:
      - "5008:5008"
    volumes:
      - .:/genesys
    image: genesys:${BUILD_TIMESTAMP}
